### ISSUE TITLE
Can't find game files for The Sims 2 Starter Pack

### ISSUE THREAD

**Issue by maxizz04** [lah7/sims2-4k-ui-patch#40]
### Operating System

Windows 11

### Patcher Program Version

v0.1.0

### Describe the problem

Hey, first of all amazing idea! So i have the Sims 2 Starter Pack and it's a different Path then the original UC Version. It's C:\Program Files (x86)\The Sims 2 Starter Pack. It can't find it automatically which i understand but then i put it in manually and it still couldn't find it. Am i doing something wrong is it a bug?

**Comment by lah7** [comment]
Hi, are you using the alternate [sims2-4k-ui-patch-v0.1.0-windows-x64-for-ultimate-collection.zip](https://github.com/lah7/sims2-4k-ui-patch/releases/download/v0.1.0/sims2-4k-ui-patch-v0.1.0-windows-x64-for-ultimate-collection.zip) version? The main patcher at the moment expects a folder structure for retail discs.

This _alternate_ v0.1.0 patcher version tweaked the code to find any folder named `*Sims 2*`, so picking `C:\Program Files (x86)` as the "EA GAMES" folder should recognise the game files, assuming the files are laid out in the same way as the Ultimate Collection. This is just until I properly fix #39.

Since I've not used this unofficial Starter Pack, please could you show me a screenshot of how this folder is laid out?

**Comment by maxizz04** [comment]
Hey thanks for replying! So i figured it kinda out. Looks like it only recognizes it if the path is exactly called C:\Program Files (x86)\EA Games\The Sims 2 Ultimate Collection. I renamed the folder from The Sims 2 Starter Pack to The Sims 2 Ultimate Collection and put it in a EA Games Folder. I have a 2k screen, so i thought i'd give it a try. Doesn't really work for me what'd make sense since this fix is desigend for 4k monitors but still nice work! Btw i first tried to just put the Starter Pack folder in a EA folder and it didn't recognised it until i renamed it. I've got an error message. Maybe it can help you if you attend to work on this or adjust something.
![Screenshot 2024-06-24 205758](https://github.com/lah7/sims2-4k-ui-patch/assets/173711708/426513b6-6d2d-4bf6-9971-92118797d8ae)

**Comment by lah7** [comment]
Thanks! Everything is a work in progress, and it is an imperfect 'preview/alpha' state at the moment. 

Please could you show me the file structure of The Sims 2 Starter Pack? Is it anything like the Ultimate Collection?

```
'Best of Business'  'Double Deluxe'  'Glamour Life Stuff'  'University Life'
'Bon Voyage'        'Fun with Pets'   Seasons
```

They store each expansion/stuff pack in folders like so:

    EP3  SP5  SP7  VP6

The error could be that the file structure are different again to retail discs and the Ultimate Collection. Once I fix #39, it won't matter where the files are. For now, I can hack a build together if you let me know the structure. We could also try 2K if you like.

**Comment by maxizz04** [comment]
It's layed out like that. A fix for 2K if it's something you'd consider would be awesome but you know don't stress yourself for anyone.
![Screenshot 2024-06-24 222224](https://github.com/lah7/sims2-4k-ui-patch/assets/173711708/02675f5a-dad5-4274-884d-c398497c5bdd)
![Screenshot 2024-06-24 222228](https://github.com/lah7/sims2-4k-ui-patch/assets/173711708/32971e17-1086-4a87-9082-f144d9ec63ec)

**Comment by lah7** [comment]
Good to know! 📂 🔍 

Don't worry, hacking the code to _make it work a certain way_ is easy. Doing it properly (#37) needs more time.

I've created two commits. Both should recognise The Sims 2 Starter Pack by selecting the folder.

* 494193d3cfbe30ae353ce119ea556e470e8be756 - for 2K  - [(download)](https://github.com/lah7/sims2-4k-ui-patch/actions/runs/9652310204/artifacts/1633420972)
* 1bb58c92ff7ee6a830845201d1a651072d5248d4 - for 4K - [(download)](https://github.com/lah7/sims2-4k-ui-patch/actions/runs/9652213935/artifacts/1633393881)

They're [built by the CI system](https://github.com/lah7/sims2-4k-ui-patch/actions/workflows/build.yml?query=branch%3Ahacks_issue_40), so need to be logged in to GitHub to download. I briefly tried 2K and it seems to scale as expected, which is good, but consider it experimental and [likely to have the same visual glitches as 4K](https://github.com/lah7/sims2-4k-ui-patch/issues?q=is%3Aissue+is%3Aopen+label%3A%22visual+bug%22).

**Comment by maxizz04** [comment]
Thanks a lot. I forgot to answer. As you said, there's some visual glitches ofc, but the resolution fits.

**Comment by lah7** [comment]
Good news! The next version (v0.2.0) of the patcher added support for selecting 2K from the list, as well as correctly detecting The Sims 2 Starter pack.
