### ISSUE TITLE
Crashes with IndexError trying to patch repack version of game

### ISSUE THREAD

**Issue by littlertom** [lah7/sims2-4k-ui-patch#43]
### Operating System

Windows 11

### Patcher Program Version

v0.1.0

### Installation Type

Repack or other automated installation

### Describe the problem

Opening the patcher and reads C:\Program Files (x86)\EA Games then it crashes with error below

![SC](https://github.com/user-attachments/assets/d9bb0968-886e-4eba-8d2f-470782d8f914)

EA Games folder has read/write permissions on users, administators and trustedinstaller
I've also tried moving the folder somewhere else but it stays on Checking for patches forever...

### Traceback

```true
Traceback (most recent call last):
File
"D:\a\sims2-4k-ui-patch\sims2-4k-ui-patch\venv\Lib\site-packa
ges\cx_Freeze\initscripts\__startup__.py", line 141, in run
File
"D:\a\sims2-4k-ui-patch\sims2-4k-ui-patch\venv\Lib\site-packa
ges\cx_Freeze\initscripts\console.py", line 25, in run
File "sims2_4k_ui_patcher.py", line 503, in <module>
File "sims2_4k_ui_patcher.py", line 161, in __init__
File "sims2_4k_ui_patcher.py", line 261, in
refresh_game_status
File "D:\a\sims2-4k-ui-patch\sims2-4k-ui-patch\gamefile.py",
line 43, in __init__
IndexError: list index out of range
OK
```

**Comment by lah7** [comment]
Please try the latest build _(soon to be v0.2.0),_ this addressed issues reading non-retail versions of the game.

You can download an artifact at the bottom of here:

* https://github.com/lah7/sims2-4k-ui-patch/actions/runs/9981904831/artifacts/1712716462
* (or any one else seeing this in future, the [latest build](https://github.com/lah7/sims2-4k-ui-patch/actions/workflows/build.yml) in the list)

**Comment by lah7** [comment]
[v0.2.0 has been released](https://github.com/lah7/sims2-4k-ui-patch/releases/tag/v0.2.0), which improves support for non-retail versions of the game, and fixes this error.
