### ISSUE TITLE
Support for 1440p

### ISSUE THREAD

**Issue by iTylerGqmer** [lah7/sims2-4k-ui-patch#48]
I love this patcher but my main monitors resolution is 2560x1440 so whenever I apply this patch the ui is a little too big. A 1440p version would be great.

**Comment by lah7** [comment]
Good news - 1440p is an option in the latest patcher code. There just hasn't been a new release yet.

You can download an _artifact_ with the most recent patcher build (at time of writing) here:

* https://github.com/lah7/sims2-4k-ui-patch/actions/runs/10432675313/artifacts/1822992739

_(For any one seeing this in the future, find `build-windows-x64` from the [latest workflow build](https://github.com/lah7/sims2-4k-ui-patch/actions/workflows/build.yml?query=event%3Apush) list)_

I'll close this issue once a release is out with 1440p support.

**Comment by lah7** [comment]
[v0.2.0 has been released](https://github.com/lah7/sims2-4k-ui-patch/releases/tag/v0.2.0), which adds support for 2K.
